### ISSUE TITLE
topics/categories update

### ISSUE THREAD

**Issue by arantzardzm** [simonseo/nyuad-spammer#31]
Student Portal has changed the categories. Need to decide whether to:

1. Users subscribe to everything
2. Update all topics/categories

We choose 1. Not because we are lazy though.

**Comment by arantzardzm** [comment]
Update spammer.js and index.js to remove individual category subscription

**Comment by simonseo** [comment]
We decided to keep the current infrastructure, but change the front end so that users don't manually type in everything and instead we'll subscribe the user to all categories & topics.

In the back, we'll need to update the categories & topics list according to the new ones.

- [X] `getUserSubs.py` does not need to change.
- [ ] `dbsetup.py` should reflect new topics
